/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;
import java.awt.event.*;
import javax.swing.JOptionPane;

/**
 *
 * @author rene
 */
public class ConversorMoneda extends javax.swing.JFrame {

    /**
     * Creates new form ConversorMoneda
     */
    public ConversorMoneda() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnConvertir = new javax.swing.JButton();
        radioDolar = new javax.swing.JRadioButton();
        radioMxDolar = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        radioEuro = new javax.swing.JRadioButton();
        radioMxEuro = new javax.swing.JRadioButton();
        txtResultado = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        radioLibra = new javax.swing.JRadioButton();
        radioMxLibra = new javax.swing.JRadioButton();
        btnNuevo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        radioYen = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        radioMxYen = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        radioWon = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        radioMxWon = new javax.swing.JRadioButton();
        labelResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de moneda");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cantidad");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Convertir de pesos a ");

        btnConvertir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnConvertir.setText("Convertir");
        btnConvertir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        Grupo1.add(radioDolar);
        radioDolar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioDolar.setText("Doláres");

        Grupo1.add(radioMxDolar);
        radioMxDolar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioMxDolar.setText("Pesos");
        radioMxDolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMxDolarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Convertir de pesos a ");

        Grupo1.add(radioEuro);
        radioEuro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioEuro.setText("Euros");

        Grupo1.add(radioMxEuro);
        radioMxEuro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioMxEuro.setText("Pesos");
        radioMxEuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMxEuroActionPerformed(evt);
            }
        });

        txtResultado.setBorder(null);
        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Desarrollo  by Rene Everardo Contreras Arias");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(15, 15, 15))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Convertir de  pesos a ");

        Grupo1.add(radioLibra);
        radioLibra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioLibra.setText("Libra Esterlina");

        Grupo1.add(radioMxLibra);
        radioMxLibra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioMxLibra.setText("Pesos");

        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Convertir de dolares a ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Convertir de euros a ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Convertir de libras a ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Convertidor de Monedas");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Convertir de  pesos a ");

        Grupo1.add(radioYen);
        radioYen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioYen.setText("Yen");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Convertir de yenes a ");

        Grupo1.add(radioMxYen);
        radioMxYen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioMxYen.setText("Pesos");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Convertir de  pesos a ");

        Grupo1.add(radioWon);
        radioWon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioWon.setText("Won");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Convertir de wons a ");

        Grupo1.add(radioMxWon);
        radioMxWon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioMxWon.setText("Pesos");

        labelResultado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelResultado.setText("Resultado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioEuro)
                            .addComponent(radioDolar)
                            .addComponent(radioLibra)
                            .addComponent(radioYen)
                            .addComponent(radioWon))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radioMxEuro, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(radioMxLibra, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(137, 137, 137))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radioMxYen)
                                            .addComponent(radioMxWon))
                                        .addContainerGap())))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioMxDolar)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnConvertir)
                        .addGap(38, 38, 38)
                        .addComponent(labelResultado)
                        .addGap(18, 18, 18)
                        .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(350, 350, 350))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel4))
                            .addComponent(jLabel10)
                            .addComponent(btnNuevo)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(btnSalir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuevo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConvertir)
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelResultado))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(radioDolar)
                    .addComponent(jLabel5)
                    .addComponent(radioMxDolar))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(radioEuro)
                    .addComponent(jLabel7)
                    .addComponent(radioMxEuro))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(radioLibra)
                    .addComponent(jLabel8)
                    .addComponent(radioMxLibra))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(radioYen)
                    .addComponent(jLabel11)
                    .addComponent(radioMxYen))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(radioWon)
                    .addComponent(jLabel13)
                    .addComponent(radioMxWon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioMxDolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMxDolarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMxDolarActionPerformed

    private void radioMxEuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMxEuroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMxEuroActionPerformed

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        Salir salir = new Salir();
        salir.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        // TODO add your handling code here:
     /*   String texto;
        texto = txtCantidad.getText();
        txtResultado.setText(texto); */
        
        try {
            
            double cantidad = Double.parseDouble(txtCantidad.getText());
             double resultado;
             String dolar =" dolares";
             String peso = " pesos";
             String euro = " euros";
             String libra = " libras esterlinas";
             String yen = " yens";
             String won = " wons";
              if (radioDolar.isSelected()) {
                    resultado = cantidad * 0.05; // Tipo de cambio al 3 de abril de 2023
                    txtResultado.setText(String.format("%.2f", resultado)+ dolar);
                    
                } else if(radioMxDolar.isSelected()) {
                    resultado = cantidad * 18.07; // Tipo de cambio al 3 de abril de 2023
                    txtResultado.setText(String.format("%.2f", resultado)+peso);
                }else if(radioEuro.isSelected()) {
                    resultado = cantidad * 0.06; // Tipo de cambio al 3 de abril de 2023
                    txtResultado.setText(String.format("%.2f", resultado)+ euro);
                }else if(radioMxEuro.isSelected()) {
                    resultado = cantidad * 19.72; // Tipo de cambio al 3 de abril de 2023
                    txtResultado.setText(String.format("%.2f", resultado)+ peso);
                }else if(radioLibra.isSelected()) {
                    resultado = cantidad * 0.04; // Tipo de cambio al 3 de abril de 2023
                    txtResultado.setText(String.format("%.2f", resultado)+ libra);
                }else if(radioMxLibra.isSelected()) {
                    resultado = cantidad * 22.47; // Tipo de cambio al 3 de abril de 2023
                    txtResultado.setText(String.format("%.2f", resultado)+ peso);
                }else if(radioYen.isSelected()) {
                    resultado = cantidad * 0.14; // Tipo de cambio al 3 de abril de 2023
                    txtResultado.setText(String.format("%.2f", resultado)+ yen);
                }else if(radioMxYen.isSelected()) {
                    resultado = cantidad * 7.27; // Tipo de cambio al 3 de abril de 2023
                    txtResultado.setText(String.format("%.2f", resultado)+ peso);
                }else if(radioWon.isSelected()) {
                    resultado = cantidad * 0.01; // Tipo de cambio al 3 de abril de 2023
                    txtResultado.setText(String.format("%.2f", resultado)+ won);
                }else if(radioMxWon.isSelected()) {
                    resultado = cantidad * 72.53; // Tipo de cambio al 3 de abril de 2023
                    txtResultado.setText(String.format("%.2f", resultado)+ peso);
                }
              
               // Mostrar el resultado en el campo de texto correspondiente
          /*      if (radioDolar.isSelected()) {
                    txtResultado.setText(String.format("%.2f", resultado));
                } else if(radioMxDolar.isSelected()){
                    
                }*/
             
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, "Ingrese una cantidad válida", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConvertirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        borrar();
    }//GEN-LAST:event_btnNuevoActionPerformed

        public void borrar(){
            
            txtCantidad.setText("");
            txtResultado.setText("");
            
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorMoneda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Grupo1;
    private javax.swing.JButton btnConvertir;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JRadioButton radioDolar;
    private javax.swing.JRadioButton radioEuro;
    private javax.swing.JRadioButton radioLibra;
    private javax.swing.JRadioButton radioMxDolar;
    private javax.swing.JRadioButton radioMxEuro;
    private javax.swing.JRadioButton radioMxLibra;
    private javax.swing.JRadioButton radioMxWon;
    private javax.swing.JRadioButton radioMxYen;
    private javax.swing.JRadioButton radioWon;
    private javax.swing.JRadioButton radioYen;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
